author: Kathrin Gruber
markdown: kramdown
title: Introduction to R
description: Marketing Analytics and Data Science
theme: minima
permalink: /:categories/

header_pages:
  - A_Primer_on_R.md
  - Base_R.md
  
