author: Kathrin Gruber
markdown: kramdown
title: Introduction to R
description: Workshop on Marketing Analytics and Data Science
theme: minima
permalink: /:categories/

header_pages:
  - A_Primer_on_R.md
  - Base_R.md
  
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

